services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mongodb-backup-api
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/mongo-backups:/backups
    restart: unless-stopped
